name = "PicoQuantHistograms"
uuid = "8c1719cd-51b0-429c-ba23-5276ff4fdee9"
authors = ["Hugo Levy-Falk <klafyvel@klafyvel.me> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
